module.exports = {
    symbols: {  
        success:{name:'Success', code:''},
        failure:{name:'Failure', code:''},
        advantage:{name:'Advantage', code:''},
        threat:{name:'Threat', code:''},
        triumph:{name:'Triumph', code:''},
        despair:{name:'Despair', code:''},
        dark:{name:'Dark', code:''},
        light:{name:'Light', code:''}
    },

    ability: [  
        {  
            results:[  
                'Success'
            ],
            code:'',
            face:'Abil1S'
        },
        {  
            results:[  
                'Advantage'
            ],
            code:'',
            face:'Abil1A'
        },
        {  
            results:[  
                'Success',
                'Advantage'
            ],
            code:'',
            face:'Abil1A1S'
        },
        {  
            results:[  
                'Success',
                'Success'
            ],
            code:'',
            face:'Abil2S'
        },
        {  
            results:[  
                'Advantage'
            ],
            code:'',
            face:'Abil1A'
        },
        {  
            results:[  
                'Success'
            ],
            code:'',
            face:'Abil1S'
        },
        {  
            results:[  
                'Advantage',
                'Advantage'
            ],
            code:'',
            face:'Abil2A'
        },
        {  
            results:[  
                'Blank'
            ],
            code:'',
            face:'AbilBla'
        }
    ],

    difficulty: [  
        {  
            results:[  
                'Threat'
            ],
            code:'',
            face:'Diff1T'
        },
        {  
            results:[  
                'Failure'
            ],
            code:'',
            face:'Diff1F'
        },
        {  
            results:[  
                'Threat',
                'Failure'
            ],
            code:'',
            face:'Diff1T1F'
        },
        {  
            results:[  
                'Threat'
            ],
            code:'',
            face:'Diff1T'
        },
        {  
            results:[  
                'Blank'
            ],
            code:'',
            face:'DiffBla'
        },
        {  
            results:[  
                'Threat',
                'Threat'
            ],
            code:'',
            face:'Diff2T'
        },
        {  
            results:[  
                'Failure',
                'Failure'
            ],
            code:'',
            face:'Diff2F'
        },
        {  
            results:[  
                'Threat'
            ],
            code:'',
            face:'Diff1T'
        }
    ],

    setback: [  
        {  
            results:[  
                'Threat'
            ],
            code:'',
            face:'Setb1T'
        },
        {  
            results:[  
                'Threat'
            ],
            code:'',
            face:'Setb1T'
        },
        {  
            results:[  
                'Failure'
            ],
            code:'',
            face:'Setb1F'
        },
        {  
            results:[  
                'Failure'
            ],
            code:'',
            face:'Setb1F'
        },
        {  
            results:[  
                'Blank'
            ],
            code:'',
            face:'SetbBla'
        },
        {  
            results:[  
                'Blank'
            ],
            code:'',
            face:'SetbBla'
        }
    ],

    boost: [  
        {  
            results:[  
                'Success'
            ],
            code:'',
            face:'Boos1S'
        },
        {  
            results:[  
                'Advantage'
            ],
            code:'',
            face:'Boos1A'
        },
        {  
            results:[  
                'Advantage',
                'Advantage'
            ],
            code:'',
            face:'Boos2A'
        },
        {  
            results:[  
                'Success',
                'Advantage'
            ],
            code:'',
            face:'Boos1A1S'
        },
        {  
            results:[  
                'Blank'
            ],
            code:'',
            face:'BoosBla'
        },
        {  
            results:[  
                'Blank'
            ],
            code:'',
            face:'BoosBla'
        }
    ],

    proficiency: [  
        {  
            results:[  
                'Advantage',
                'Advantage'
            ],
            code:'',
            face:'Prof2A'
        },
        {  
            results:[  
                'Advantage'
            ],
            code:'',
            face:'Prof1A'
        },
        {  
            results:[  
                'Advantage',
                'Advantage'
            ],
            code:'',
            face:'Prof2A'
        },
        {  
            results:[  
                'Triumph'
            ],
            code:'',
            face:'ProfTri'
        },
        {  
            results:[  
                'Success'
            ],
            code:'',
            face:'Prof1S'
        },
        {  
            results:[  
                'Success',
                'Advantage'
            ],
            code:'',
            face:'Prof1A1S'
        },
        {  
            results:[  
                'Success'
            ],
            code:'',
            face:'Prof1S'
        },
        {  
            results:[  
                'Success',
                'Advantage'
            ],
            code:'',
            face:'Prof1A1S'
        },
        {  
            results:[  
                'Success',
                'Success'
            ],
            code:'',
            face:'Prof2S'
        },
        {  
            results:[  
                'Success',
                'Advantage'
            ],
            code:'',
            face:'Prof1A1S'
        },
        {  
            results:[  
                'Success',
                'Success'
            ],
            code:'',
            face:'Prof2S'
        },
        {  
            results:[  
                'Blank'
            ],
            code:'',
            face:'ProfBla'
        }
    ],

    challenge: [  
        {  
            results:[  
                'Threat',
                'Threat'
            ],
            code:'',
            face:'Chal2T'
        },
        {  
            results:[  
                'Threat'
            ],
            code:'',
            face:'Chal1T'
        },
        {  
            results:[  
                'Threat',
                'Threat'
            ],
            code:'',
            face:'Chal2T'
        },
        {  
            results:[  
                'Threat'
            ],
            code:'',
            face:'Chal1T'
        },
        {  
            results:[  
                'Threat',
                'Failure'
            ],
            code:'',
            face:'Chal1T1F'
        },
        {  
            results:[  
                'Failure'
            ],
            code:'',
            face:'Chal1F'
        },
        {  
            results:[  
                'Threat',
                'Failure'
            ],
            code:'',
            face:'Chal1T1F'
        },
        {  
            results:[  
                'Failure'
            ],
            code:'',
            face:'Chal1F'
        },
        {  
            results:[  
                'Failure',
                'Failure'
            ],
            code:'',
            face:'Chal2F'
        },
        {  
            results:[  
                'Despair'
            ],
            code:'',
            face:'ChalDes'
        },
        {  
            results:[  
                'Failure',
                'Failure'
            ],
            code:'',
            face:'Chal2F'
        },
        {  
            results:[  
                'Blank'
            ],
            code:'',
            face:'ChalBla'
        }
    ],

    force: [  
        {  
            results:[  
                'Light',
                'Light'
            ],
            code:'',
            face:'Forc2L'
        },
        {  
            results:[  
                'Light',
                'Light'
            ],
            code:'',
            face:'Forc2L'
        },
        {  
            results:[  
                'Light',
                'Light'
            ],
            code:'',
            face:'Forc2L'
        },
        {  
            results:[  
                'Light'
            ],
            code:'',
            face:'Forc1L'
        },
        {  
            results:[  
                'Light'
            ],
            code:'',
            face:'Forc1L'
        },
        {  
            results:[  
                'Dark',
                'Dark'
            ],
            code:'',
            face:'Forc2D'
        },
        {  
            results:[  
                'Dark'
            ],
            code:'',
            face:'Forc1D'
        },
        {  
            results:[  
                'Dark'
            ],
            code:'',
            face:'Forc1D'
        },
        {  
            results:[  
                'Dark'
            ],
            code:'',
            face:'Forc1D'
        },
        {  
            results:[  
                'Dark'
            ],
            code:'',
            face:'Forc1D'
        },
        {  
            results:[  
                'Dark'
            ],
            code:'',
            face:'Forc1D'
        },
        {  
            results:[  
                'Dark'
            ],
            code:'',
            face:'Forc1D'
        }
    ]
};